# Generated by Django 3.2.3 on 2021-06-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('fname', models.CharField(max_length=10)),
                ('exp', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='clint',
            name='cname',
        ),
        migrations.AddField(
            model_name='clint',
            name='name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
