# Generated by Django 3.2.3 on 2021-06-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsadmin', '0002_auto_20210614_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('knowledge', models.CharField(max_length=50)),
                ('exp', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
