# Generated by Django 3.2.3 on 2021-06-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsadmin', '0004_alogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=50)),
                ('exp', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=10)),
            ],
        ),
    ]
