# Generated by Django 3.2.3 on 2021-06-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsadmin', '0005_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='clint',
            name='cname',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
