# Generated by Django 3.2.3 on 2021-06-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsadmin', '0006_clint_cname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('ststus', models.CharField(max_length=10)),
                ('ccom', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=25)),
                ('estbudget', models.CharField(max_length=10)),
                ('estamt', models.CharField(max_length=10)),
                ('estdur', models.CharField(max_length=10)),
            ],
        ),
    ]
