# Generated by Django 3.2.3 on 2021-06-19 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsadmin', '0007_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='ststus',
            new_name='status',
        ),
    ]
