# Generated by Django 3.2.3 on 2021-06-20 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsadmin', '0009_auto_20210620_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr',
            old_name='aboout',
            new_name='about',
        ),
    ]
