# Generated by Django 3.2.3 on 2021-06-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsadmin', '0010_rename_aboout_hr_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='education',
            field=models.CharField(max_length=30),
        ),
    ]
