# Generated by Django 3.2.3 on 2021-06-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsadmin', '0012_rename_aboout_clint_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devlopers',
            old_name='aboout',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='managers',
            old_name='aboout',
            new_name='about',
        ),
    ]
