# Generated by Django 3.2.3 on 2021-09-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsadmin', '0014_alter_managers_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.CharField(max_length=30)),
                ('managerid', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='clint',
            name='cname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='clint',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='clint',
            name='location',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='clint',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='clint',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='clint',
            name='pname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='devlopers',
            name='designation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='devlopers',
            name='education',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='devlopers',
            name='exp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='devlopers',
            name='location',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='devlopers',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='devlopers',
            name='salary',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='hr',
            name='education',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='hr',
            name='exp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hr',
            name='location',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='hr',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='hr',
            name='salary',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='managers',
            name='age',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='managers',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='managers',
            name='exp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='managers',
            name='location',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='managers',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='managers',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='managers',
            name='salary',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='ccom',
            field=models.CharField(max_length=40),
        ),
    ]
